FROM aursu/rpmbuild:7-build

USER root
RUN yum -y install \
        gnutls-utils \
        groff \
        libidn2-devel \
        libnghttp2-devel \
        libpsl-devel \
        nghttp2 \
        openssl-devel \
        perl-Digest-MD5 \
        stunnel \
        zlib-devel \
    && yum clean all && rm -rf /var/cache/yum
