version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      BINTRAY_REPO: custom
      ARTIFACTORY_URL: https://rpmb.jfrog.io
    steps:
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Pull images for RPM build docker services
          command: |
            docker-compose -f rpmbuild/docker-compose.yml pull
            docker-compose -f rpmbuild/docker-compose.bintray.yml pull
      - run:
          name: Build PHP Docker images
          command: docker-compose build --no-cache
      - run:
          name: Build RPM packages
          command: docker-compose up
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e ARTIFACTORY_URL=$ARTIFACTORY_URL centos7bintray
